# This is a basic workflow to help you get started with Actions

on:
  push:
    branches: main
  workflow_dispatch:
jobs:
  Windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.2
      - name: Setup Haxelib
        run: |
          haxelib setup C:\haxelib
          haxelib install flixel 5.5.0 --never
          haxelib install flixel-addons 3.2.1 --never
          haxelib install flixel-ui 2.5.0 --never
          haxelib git flxanimate https://github.com/ShadowMario/flxanimate --never
          haxelib install hscript 2.5.0
          haxelib install hxgamejolt-api 1.2.0
          haxelib install lime 8.0.1 --never
          haxelib install openfl 9.3.2   --never
          haxelib install tjson 1.4.0 --never
          haxelib git moonchart https://github.com/MaybeMaru/moonchart --never
          haxelib install hxcpp 4.3.2 --never
          haxelib list
        shell: cmd
      - name: Compile
        run: |
          haxelib run lime build cpp
        shell: cmd
      - name: Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Example
          path: export/release/windows/bin
