
name: Windows Build
on:
  push:
  workflow_dispatch:
jobs:
  build:
    name: Windows Build
    permissions: write-all
    runs-on: windows-latest
    steps:
      - name: Pulling the new commit
        uses: actions/checkout@v2
      - name: Setting up Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.2
      - name: Restore existing build cache for faster compilation
        uses: actions/cache@v3
        with:
          # not caching the bin folder to prevent asset duplication and stuff like that
          key: cache-build-windows
          path: |
            .haxelib/
            export/release/windows/haxe/
            export/release/windows/obj/
          restore-keys: |
            cache-build-windows
      - name: Installing/Updating libraries
        run: |
       
          haxelib setup C:\haxelib
          mkdir export
          haxelib install flixel 5.5.0 --never
          haxelib install flixel-addons 3.2.1 --never
          haxelib install flixel-ui 2.5.0 --never
          haxelib git flxanimate https://github.com/ShadowMario/flxanimate --never
          haxelib install hscript 2.5.0
          haxelib install hxgamejolt-api 1.2.0
          haxelib install lime 8.0.1 --never
          haxelib install openfl 9.3.2   --never
          haxelib install tjson 1.4.0 --never
          haxelib git moonchart https://github.com/MaybeMaru/moonchart --never
          haxelib install hxcpp 4.3.2 --never
          haxelib git haxeui-flixel https://github.com/haxeui/haxeui-flixel --never 
          haxelib git haxeui-core https://github.com/haxeui/haxeui-core --never --skip-dependencies
          haxelib git hxdiscord_rpc https://github.com/MAJigsaw77/hxdiscord_rpc --never
          haxelib install hxCodec --never
          haxelib list
          

      - name: Building the game
        run: |
          haxelib run lime build windows
          dir
      - name: Uploading artifact (entire build)
        uses: actions/upload-artifact@v4
        with:
          name: Hyper Engine
          path: export/windows/bin
      # - name: Uploading artifact (executable)
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: Update-Windows
      #     path: export/release/windows/bin/CodenameEngine.exe
      - name: Clearing already existing cache
        uses: actions/github-script@v6
        with:
          script: |
            const caches = await github.rest.actions.getActionsCacheList({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            for (const cache of caches.data.actions_caches) {
              if (cache.key == "cache-build-windows") {
                console.log('Clearing ' + cache.key + '...')
                await github.rest.actions.deleteActionsCacheById({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  cache_id: cache.id,
                })
                console.log("Cache cleared.")
              }
            }
      - name: Uploading new cache
        uses: actions/cache@v3
        with:
          # caching again since for some reason it doesnt work with the first post cache shit
          key: cache-build-windows
          path: |
            .haxelib/
            export/windows/haxe/
            export/windows/obj/
          restore-keys: |
            cache-build-windows
